name: focustrack
description: "A cross-platform screen time tracker for desktop."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.3
  path: ^1.9.0
  win32: ^5.0.0
  dotup_flutter_active_window: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
